#use_frameworks!

platform :ios, '8.0'

target 'YTNetWork_Example' do
  pod 'YTNetWork', :path => '../'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'YTKNetwork'
  pod 'MJExtension'
  target 'YTNetWork_Tests' do
    inherit! :search_paths

    
  end
end
